### PR TITLE
Feature/deploy frontend

### PR DESCRIPTION
**Pull request by aviadg-at-kela**
# Description

Connect to backend.

Fixes # (if relevant)

## Type of change

Please delete options that are not relevant.

- [ x ] New feature

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**If this is a UI change / fix, please also add a screenshot**

# Checklist:

- [ x ] I have performed a self-review of my own code
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Nice! Let me review the code for a second.

**Review by vanessa-cooper — DISMISSED** [review]
Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

**Comment by aviadg-at-kela** [comment]
Fixed

**Review by vanessa-cooper — APPROVED** [review]
Done! The frontend is now connected to the correct backend. Don’t forget to merge the PR.

**Pull request merged**
